services:
  postgres:
    container_name: postgres-set-reservation
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reservation_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-seat-reservation-data:/var/lib/postgresql/data
    
volumes:
  postgres-seat-reservation-data:
