// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeatReservation.Infrastructure.Postgres;

#nullable disable

namespace SeatReservation.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ReservationServiceDbContext))]
    [Migration("20251211125417_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("info");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("VenueId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Event.EventDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReservationUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_event_details");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_details", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_resevations");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.ReservationSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ReservationAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Guid>("reservation_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_reservation_seats");

                    b.HasIndex("SeatId");

                    b.HasIndex("reservation_id");

                    b.HasIndex("EventId", "SeatId")
                        .IsUnique();

                    b.ToTable("reservation_seats", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("VenueId");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxSeatsCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_seats_count");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SeatReservationDomain.Event.EventDates", "Dates", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("EventDate")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("event_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("start_date");

                            b1.HasKey("EventId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("SeatReservationDomain.Event.EventName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("EventId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Dates")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Event.EventDetails", b =>
                {
                    b.HasOne("SeatReservationDomain.Event.Event", null)
                        .WithOne("Details")
                        .HasForeignKey("SeatReservationDomain.Event.EventDetails", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SeatReservationDomain.Event.EventCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("EventDetailsId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("capacity");

                            b1.HasKey("EventDetailsId");

                            b1.ToTable("event_details");

                            b1.WithOwner()
                                .HasForeignKey("EventDetailsId");
                        });

                    b.OwnsOne("SeatReservationDomain.Event.EventDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("EventDetailsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.HasKey("EventDetailsId");

                            b1.ToTable("event_details");

                            b1.WithOwner()
                                .HasForeignKey("EventDetailsId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.ReservationSeat", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeatReservationDomain.Reservation.Reservation", "Reservation")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("reservation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SeatReservationDomain.Users.User", b =>
                {
                    b.OwnsOne("SeatReservationDomain.Users.Details", "Details", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.ToJson("details");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("SeatReservationDomain.Users.Fio", "FIO", b2 =>
                                {
                                    b2.Property<Guid>("DetailsUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("fio");

                                    b2.HasKey("DetailsUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("DetailsUserId");
                                });

                            b1.OwnsMany("SeatReservationDomain.Users.SocialNetwork", "Socials", b2 =>
                                {
                                    b2.Property<Guid>("DetailsUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.HasKey("DetailsUserId", "__synthesizedOrdinal");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("DetailsUserId");

                                    b2.OwnsOne("SeatReservationDomain.Users.SocialNetworkLink", "Link", b3 =>
                                        {
                                            b3.Property<Guid>("SocialNetworkDetailsUserId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("SocialNetwork__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(1000)
                                                .HasColumnType("character varying(1000)")
                                                .HasColumnName("link");

                                            b3.HasKey("SocialNetworkDetailsUserId", "SocialNetwork__synthesizedOrdinal");

                                            b3.ToTable("users");

                                            b3.WithOwner()
                                                .HasForeignKey("SocialNetworkDetailsUserId", "SocialNetwork__synthesizedOrdinal");
                                        });

                                    b2.OwnsOne("SeatReservationDomain.Users.SocialNetworkName", "Name", b3 =>
                                        {
                                            b3.Property<Guid>("SocialNetworkDetailsUserId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("SocialNetwork__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(3000)
                                                .HasColumnType("character varying(3000)")
                                                .HasColumnName("name");

                                            b3.HasKey("SocialNetworkDetailsUserId", "SocialNetwork__synthesizedOrdinal");

                                            b3.ToTable("users");

                                            b3.WithOwner()
                                                .HasForeignKey("SocialNetworkDetailsUserId", "SocialNetwork__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Link")
                                        .IsRequired();

                                    b2.Navigation("Name")
                                        .IsRequired();
                                });

                            b1.OwnsOne("SeatReservationDomain.Users.UserDescription", "Description", b2 =>
                                {
                                    b2.Property<Guid>("DetailsUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("description");

                                    b2.HasKey("DetailsUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("DetailsUserId");
                                });

                            b1.Navigation("Description")
                                .IsRequired();

                            b1.Navigation("FIO")
                                .IsRequired();

                            b1.Navigation("Socials");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Seat", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Venue", "Venue")
                        .WithMany("Seats")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Venue", b =>
                {
                    b.OwnsOne("SeatReservationDomain.Venue.VenueName", "Name", b1 =>
                        {
                            b1.Property<Guid>("VenueId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("prefix");

                            b1.HasKey("VenueId");

                            b1.ToTable("venues");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.Reservation", b =>
                {
                    b.Navigation("ReservedSeats");
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Venue", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
