// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeatReservation.Infrastructure.Postgres;

#nullable disable

namespace SeatReservation.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ReservationServiceDbContext))]
    [Migration("20250907133127_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("event_date");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("VenueId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Event.EventDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("LastReservationUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_event_details");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_details", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_resevations");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.ReservationSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ReservationAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Guid>("reservation_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_reservation_seats");

                    b.HasIndex("SeatId");

                    b.HasIndex("reservation_id");

                    b.HasIndex("EventId", "SeatId")
                        .IsUnique();

                    b.ToTable("reservation_seats", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("VenueId");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MaxSeatsCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_seats_count");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "SeatReservationDomain.Venue.Venue.Name#VenueName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("prefix");
                        });

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Event.EventDetails", b =>
                {
                    b.HasOne("SeatReservationDomain.Event.Event", null)
                        .WithOne("Details")
                        .HasForeignKey("SeatReservationDomain.Event.EventDetails", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.ReservationSeat", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeatReservationDomain.Reservation.Reservation", "Reservation")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("reservation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SeatReservationDomain.Users.User", b =>
                {
                    b.OwnsOne("SeatReservationDomain.Users.Details", "Details", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<string>("FIO")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("foi");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.ToJson("details");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("SeatReservationDomain.Users.SocialNetwork", "Socials", b2 =>
                                {
                                    b2.Property<Guid>("DetailsUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Link")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("link");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("name");

                                    b2.HasKey("DetailsUserId", "__synthesizedOrdinal");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("DetailsUserId");
                                });

                            b1.Navigation("Socials");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Seat", b =>
                {
                    b.HasOne("SeatReservationDomain.Venue.Venue", "Venue")
                        .WithMany("Seats")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SeatReservationDomain.Event.Event", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("SeatReservationDomain.Reservation.Reservation", b =>
                {
                    b.Navigation("ReservedSeats");
                });

            modelBuilder.Entity("SeatReservationDomain.Venue.Venue", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
